const videos = [
  {
    id: 1,
    title: 'Elden Ring: Começando bem',
    channel: 'Filipe Ramos',
    views: '385 mil visualizações',
    date: 'há 2 semana',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb1.jpg',
  },
  {
    id: 2,
    title: 'Elden Ring - Guia Básico de Iniciantes',
    channel: 'Filipe Ramos',
    views: '365 mil visualizações',
    date: 'há 2 semana',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb2.jpg',
  },
  {
    id: 3,
    title: 'Pathologic 2: Um Diamante no Mundo dos Jogos',
    channel: 'Filipe Ramos',
    views: '3,5 mi de visualizações',
    date: 'há 1 ano',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb3.jpg',
  },
  {
    id: 4,
    title: 'Dark Souls 3: Começando Bem',
    channel: 'Filipe Ramos',
    views: '1,4 mi de visualizações',
    date: 'há 5 anos',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb4.jpg',
  },
  {
    id: 5,
    title: 'Fallout 76: Tudo que Você Precisa Saber (Desatualizado)',
    channel: 'Filipe Ramos',
    views: '1,4 mi de visualizações',
    date: 'há 3 anos',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb5.jpg',
  },
  {
    id: 6,
    title: 'Resident Evil 8: Resumo da Primeira Jogada (1/2)',
    channel: 'Filipe Ramos',
    views: '880 mil visualizações',
    date: 'há 10 semanas',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb6.jpg',
  },
  {
    id: 7,
    title: 'Resident Evil 2 Remake: Guia Para Rank S+ no Insano',
    channel: 'Filipe Ramos',
    views: '2,5 mi de visualizações',
    date: 'há 3 anos',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb7.jpg',
  },
  {
    id: 8,
    title:
      'Resident Evil 3 Remake: Eu Comparando Ele Com o Clássico e Reclamando Por Meia Hora',
    channel: 'Filipe Ramos',
    views: '1,4 mi de visualizações',
    date: 'há 1 anos',
    avatar: '/images/filipeRamos.jpg',
    thumb: '/images/thumb8.jpg',
  },
];

export default videos;
